import {
  Button,
  Divider,
  Flex,
  Heading,
  SimpleGrid,
  Spacer,
  Text,
  VStack,
  Image,
  Input,
  Box,
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import Card from '../components/Card';
import Header from '../components/Header';

const Home: NextPage = () => {
  const [apples, setApples] = useState(0);
  const [oranges, setOranges] = useState(0);
  const [mango, setMango] = useState(0);
  const [banana, setBanana] = useState(0);

  return (
    <div>
      <Head>
        <title>
          CDL software coding challenge in nextjs,typescript and chakra UI
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      {/* <div>hello</div> */}
      <Flex rounded={['none', 'md']} p='6' bgColor='white' direction='column'>
        <Flex alignItems='center'>
          <Heading fontSize='lg' ml='3'>
            Shopping Cart{' '}
          </Heading>

          <Spacer />

          <Text
            display={['none', 'flex']}
            fontFamily='Open sans'
            marginLeft='auto'
          >
            Add Items to Shopping Cart
          </Text>
        </Flex>

        <Divider w='full' borderColor='lightgrey' my='4' />
        <SimpleGrid spacing='2' minChildWidth='250px' px='200px'>
          <Card>
            <Flex>
              <Image
                borderRadius='10px'
                src='/apples.jpeg'
                alt='image of apples'
                height='200px'
                width='200px'
              />
            </Flex>
            <Flex my='20px'>
              <Button
                variant='outline'
                onClick={() => setApples((prev) => prev - 1)}
              >
                -{' '}
              </Button>
              <Button mx='10pt'>APPLE{apples !== 0 && `(${apples})`}</Button>
              <Button
                variant='outline'
                onClick={() => setApples((prev) => prev + 1)}
              >
                +{' '}
              </Button>
            </Flex>
          </Card>
          <Card>
            <Flex>
              <Image
                src='/oranges.jpeg'
                alt='image of apples'
                height='200px'
                width='200px'
                borderRadius='10px'
              />
            </Flex>
            <Flex my='20px'>
              <Button
                variant='outline'
                onClick={() => setOranges((prev) => prev - 1)}
              >
                -{' '}
              </Button>
              <Button mx='10pt'>ORANGE{oranges !== 0 && `(${oranges})`}</Button>
              <Button
                variant='outline'
                onClick={() => setOranges((prev) => prev + 1)}
              >
                +{' '}
              </Button>
            </Flex>
          </Card>
          <Card>
            <Flex>
              <Image
                src='/mangoes.jpeg'
                alt='image of apples'
                height='200px'
                width='200px'
                borderRadius='10px'
              />
            </Flex>
            <Flex my='20px'>
              <Button
                variant='outline'
                onClick={() => setMango((prev) => prev - 1)}
              >
                -{' '}
              </Button>
              <Button mx='10pt'>MANGO{mango !== 0 && `(${mango})`}</Button>
              <Button
                variant='outline'
                onClick={() => setMango((prev) => prev + 1)}
              >
                +{' '}
              </Button>
            </Flex>
          </Card>
          <Card>
            <Flex>
              <Image
                src='/bananas.jpeg'
                alt='image of apples'
                height='200px'
                width='200px'
                borderRadius='10px'
              />
            </Flex>
            <Flex my='20px'>
              <Button
                variant='outline'
                onClick={() => setBanana((prev) => prev - 1)}
              >
                -{' '}
              </Button>
              <Button mx='10pt'>BANANA{banana !== 0 && `(${banana})`}</Button>
              <Button
                variant='outline'
                onClick={() => setBanana((prev) => prev + 1)}
              >
                +{' '}
              </Button>
            </Flex>
          </Card>
        </SimpleGrid>
        <Flex mt='100px' direction='row'>
          <Flex flexGrow={1} direction='column'>
            <Heading
              color='black'
              mt='-39'
              mb='5'
              cursor='pointer'
              fontSize='3xl'
              fontWeight='500'
              _hover={{ color: 'grey' }}
            >
              Enter Todays Prices for Fruits and Offers
            </Heading>
            <Flex direction='row'>
              <VStack mr='50px' justify='flex-start'>
                <Text justifyContent='left'>Price for Apple</Text>
                <Input
                  minW='300px'
                  alignSelf='stretch'
                  bgColor='surface'
                  type='text'
                  // value={email}
                  // onChange={handleEmailInputChange}
                  variant='outline'
                  placeholder='Enter Price for Apple'
                  size='lg'
                  isRequired
                  _focus={{
                    borderColor: 'secondary',
                  }}
                />
              </VStack>
              <VStack>
                <Text>Todays Offer for Apple</Text>
                <Input
                  minW='300px'
                  alignSelf='stretch'
                  bgColor='surface'
                  type='text'
                  // value={email}
                  // onChange={handleEmailInputChange}
                  variant='outline'
                  placeholder='3 apples for'
                  size='lg'
                  isRequired
                  _focus={{
                    borderColor: 'secondary',
                  }}
                />
              </VStack>
            </Flex>
            <Flex direction='row' textAlign='start'>
              <VStack mr='50px' justify='flex-start'>
                <Text>Price for Oranges</Text>
                <Input
                  minW='300px'
                  alignSelf='stretch'
                  bgColor='surface'
                  type='text'
                  // value={email}
                  // onChange={handleEmailInputChange}
                  variant='outline'
                  placeholder='Enter Price for Oranges'
                  size='lg'
                  isRequired
                  _focus={{
                    borderColor: 'secondary',
                  }}
                />
              </VStack>
              <VStack>
                <Text>Todays Offer for Oranges</Text>
                <Input
                  minW='300px'
                  alignSelf='stretch'
                  bgColor='surface'
                  type='text'
                  // value={email}
                  // onChange={handleEmailInputChange}
                  variant='outline'
                  placeholder='3 Oranges for'
                  size='lg'
                  isRequired
                  _focus={{
                    borderColor: 'secondary',
                  }}
                />
              </VStack>
            </Flex>
            <Text textAlign='start'>Price for Mangoes</Text>
            <Input
              maxW='400px'
              alignSelf='stretch'
              bgColor='surface'
              type='text'
              // value={email}
              // onChange={handleEmailInputChange}
              variant='outline'
              placeholder='Enter Price for Mangoes'
              size='lg'
              isRequired
              _focus={{
                borderColor: 'secondary',
              }}
            />
            <Text>Price for Bananas</Text>
            <Input
              maxW='400px'
              alignSelf='stretch'
              bgColor='surface'
              type='text'
              // value={email}
              // onChange={handleEmailInputChange}
              variant='outline'
              placeholder='Enter Price for Bananas'
              size='lg'
              isRequired
              _focus={{
                borderColor: 'secondary',
              }}
            />
          </Flex>
          <Flex direction='column' flexGrow={1}>
            <Flex>
              <Box>
                <Text fontSize='2xl'>cost of all products </Text>
              </Box>
              <Spacer />
              <Text>cost</Text>
            </Flex>
            <Flex>
              <Box>
                <Text fontSize='2xl'>Promotional discount apple</Text>
              </Box>
              <Spacer />
              <Text>cost</Text>
            </Flex>
            <Flex>
              <Box>
                <Text fontSize='2xl'>Promotional discount Orange</Text>
              </Box>
              <Spacer />
              <Text>cost</Text>
            </Flex>
            <Flex>
              <Box>
                <Text fontSize='2xl'>Total Cost of all products </Text>
              </Box>
              <Spacer />
              <Text>cost</Text>
            </Flex>
          </Flex>
        </Flex>
      </Flex>
    </div>
  );
};

export default Home;
